# Generated by Django 2.2 on 2019-12-31 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elms_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.SlugField(unique=True)),
                ('profile_pic', models.ImageField(upload_to='Profile Picture')),
                ('first_name', models.CharField(help_text='First Name', max_length=100)),
                ('middle_name', models.CharField(help_text='Middle Name', max_length=100)),
                ('last_name', models.CharField(help_text='Last Name', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elms_accounts.Students')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
