# Generated by Django 2.2 on 2020-01-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
