# Generated by Django 2.2 on 2019-12-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Handouts title', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, help_text='Date Published')),
                ('file', models.FileField(help_text='Upload your file here', upload_to='handouts')),
            ],
            options={
                'verbose_name': 'Handout',
                'verbose_name_plural': 'Handouts',
            },
        ),
    ]
