# Generated by Django 2.2 on 2019-12-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('title', models.CharField(help_text='Enter your announcement title', max_length=150)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('slug', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='Enter the content of announcement', max_length=1000)),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
            },
        ),
    ]
